#!/usr/bin/env bash
# script to install nginx

sudo apt-get update

sudo apt-get install nginx -y

echo "Hello World!" | sudo tree /var/www/html/index.nginx-debian.html > /dev/null

sudo service nginx start
