#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

if ! command -v nginx &> /dev/null
then
	sudo apt-get update
	sudo apt-get install -y nginx
fi

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm;

	server_name _;

	error_page 404 /404.html;

	location / {
		try_files \$uri \$uri/ =404;
	}
}
EOF'

sudo /etc/init.d/nginx reload

sudo /etc/init.d/nginx restart

sudo /etc/init.d/nginx status
