#!/usr/bin/env bash
# Script to set up Nginx on ubuntu with a custom HTTP response header

# Update and install nginx
sudo apt-get update -y && sudo apt-get install -y nginx

sudo mkdir -p /etc/nginx/html
sudo bash -c 'echo "Hello World!" >  /var/www/html/index.nginx-debian.html'
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
        listen 80;
        listen [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;
        root   /var/www/html;
        index  index.html index.htm index.nginx-debian.html;
        location /redirect_me {
                return 301 https://www.github.com/triggerAustin/;
        }
        error_page 404 /404.html;
        location /404.html {
                root /etc/nginx/html;
                internal;
        }

}
EOF'

# Restart Nginx, to apply changes
sudo service nginx restart
