#!/usr/bin/env bash
# Script installs and configures HAProxy on Ubuntu to balance traffic between
# web-01 and web-02

# Update and install HAProxy
sudo apt-get update -y && sudo apt-get install -y haproxy

#!/usr/bin/env bash
#update package list $ install HAproxy
sudo apt-get update
sudo apt-get -y install haproxy


#Update HAproxy confirguration file to manage load using roundrobin algorithm
sudo bash -c 'cat >> /etc/haproxy/haproxy.cfg <<EOF
frontend penality
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 335953-web-01 54.196.29.210:80 check
        server 335953-web-02 54.87.217.94:80 check
EOF'

# Restarting HAproxy service
sudo service haproxy restart
