#!/usr/bin/env bash
#To infinity and beyond indefinitely With a sleep 2 in between and I am invincible!!! when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
trap 'echo "I am invincible!!!"' SIGINT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
