#!/usr/bin/env bash
#prints 'Best School' over 10 itterations printing 'bad luck' at the 4th and 'good luck' at the 8th using while
#elif else
i=1

while [ $i -lt 11 ]; do
	if [ $i -eq 4 ];then
		echo "bad luck"
	elif [ $i -eq 8 ];then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
