#!/usr/bin/env bash
#prints 'Best School' over 10 itterations printing 'bad luck' at the 4th and 'good luck' at the 8th using while
#elif else
i=1

while [ $i -lt 21 ]; do
	echo "$i"

	if [ $i -eq 4 ];then
		echo "bad luck from China"
	elif [ $i -eq 9 ];then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]; then
		echo "bad luck from Italy"
	fi
	((i++))
done
