#!/usr/bin/env bash
#prints 'Best School' over 10 itterations printing 'bad luck' at the 4th and 'good luck' at the 8th using while
#elif else
i=1

while [ $i -lt 21 ]; do
	echo "$i"

	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((i++))
done
