#!/usr/bin/env bash
#checks if file school exists, is empty and is a file
file="school"
if [ -e $file ]; then
	echo "school file exists"
	if [ -f $file ]; then
		if [ -s $file ]; then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
